-- =====================================================
-- ENERGY_ADMIN
-- =====================================================

GRANT USAGE ON DATABASE ENERGY_DB TO ROLE ENERGY_ADMIN;

GRANT USAGE ON ALL SCHEMAS IN DATABASE ENERGY_DB
TO ROLE ENERGY_ADMIN;

GRANT ALL PRIVILEGES ON DATABASE ENERGY_DB
TO ROLE ENERGY_ADMIN;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ENERGY_DB
TO ROLE ENERGY_ADMIN;

GRANT USAGE, OPERATE ON WAREHOUSE ENERGY_WH
TO ROLE ENERGY_ADMIN;


-- =====================================================
-- ENERGY_INGEST
-- Python -> RAW
-- =====================================================

GRANT USAGE ON DATABASE ENERGY_DB
TO ROLE ENERGY_INGEST;

GRANT USAGE ON SCHEMA ENERGY_DB.RAW
TO ROLE ENERGY_INGEST;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA ENERGY_DB.RAW
TO ROLE ENERGY_INGEST;


-- =====================================================
-- ENERGY_DBT
-- RAW -> STAGING -> INTERMEDIATE -> MART
-- =====================================================

GRANT USAGE ON DATABASE ENERGY_DB
TO ROLE ENERGY_DBT;

GRANT USAGE ON SCHEMA ENERGY_DB.RAW
TO ROLE ENERGY_DBT;

GRANT SELECT ON ALL TABLES IN SCHEMA ENERGY_DB.RAW
TO ROLE ENERGY_DBT;

GRANT USAGE ON SCHEMA ENERGY_DB.STAGING
TO ROLE ENERGY_DBT;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA ENERGY_DB.STAGING
TO ROLE ENERGY_DBT;

GRANT USAGE ON SCHEMA ENERGY_DB.INTERMEDIATE
TO ROLE ENERGY_DBT;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA ENERGY_DB.INTERMEDIATE
TO ROLE ENERGY_DBT;

GRANT USAGE ON SCHEMA ENERGY_DB.MART
TO ROLE ENERGY_DBT;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA ENERGY_DB.MART
TO ROLE ENERGY_DBT;


-- =====================================================
-- ENERGY_READONLY
-- Power BI
-- =====================================================

GRANT USAGE ON DATABASE ENERGY_DB
TO ROLE ENERGY_READONLY;

GRANT USAGE ON SCHEMA ENERGY_DB.MART
TO ROLE ENERGY_READONLY;

GRANT SELECT ON ALL TABLES IN SCHEMA ENERGY_DB.MART
TO ROLE ENERGY_READONLY;

GRANT SELECT ON ALL VIEWS IN SCHEMA ENERGY_DB.MART
TO ROLE ENERGY_READONLY;