USE DATABASE ENERGY_DB;
USE SCHEMA RAW;

-- ==========================================
-- CURVA DE CARGA HORÁRIA
-- ==========================================

CREATE TABLE IF NOT EXISTS CURVA_CARGA (
    ID_SUBSISTEMA VARCHAR,
    NOM_SUBSISTEMA VARCHAR,
    DIN_INSTANTE TIMESTAMP_NTZ,
    VAL_CARGAENERGIAHOMWMED FLOAT,

    -- Metadados da plataforma
    DATA_INGESTAO TIMESTAMP_NTZ,
    FONTE VARCHAR,
    ANO_REFERENCIA NUMBER
);


-- ==========================================
-- BALANÇO DE ENERGIA
-- ==========================================

CREATE TABLE IF NOT EXISTS BALANCO_ENERGIA (
    ID_SUBSISTEMA VARCHAR,
    NOM_SUBSISTEMA VARCHAR,
    DIN_INSTANTE TIMESTAMP_NTZ,
    VAL_GERHIDRAULICA FLOAT,
    VAL_GERTERMICA FLOAT,
    VAL_GEREOLICA FLOAT,
    VAL_GERSOLAR FLOAT,
    VAL_CARGA FLOAT,
    VAL_INTERCAMBIO FLOAT,

    -- Metadados da plataforma
    DATA_INGESTAO TIMESTAMP_NTZ,
    FONTE VARCHAR,
    ANO_REFERENCIA NUMBER
);